#!/usr/bin/env python3
"""Generate Rust tuning data from the extracted sensor tuning.

Inputs (in ../data, relative to this script):
  gc2607_ccms.json  -- 5 CCMs with cct, chroma [r/g, b/g], ccm[9]
  gc2607_lsc.npz    -- LSC grids (5,4,47,63) float gain, chroma (5,2), scale

Outputs:
  ../src/tuning_data.rs  -- const arrays (CCT, locus, CCM, LSC chroma, dims)
  ../data/lsc_grids.bin  -- f32 LE, order [ls][ch][gh][gw], values already gain
                            (raw/scale), included via include_bytes! in Rust.
"""
import json
import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
SRC = os.path.join(HERE, "..", "src")


def fmt_f32(x):
    return f"{float(x):.9g}f32"


def main():
    ccms = json.load(open(os.path.join(DATA, "gc2607_ccms.json")))
    ccms.sort(key=lambda c: c["cct"])
    cct = [c["cct"] for c in ccms]
    locus = [c["chroma"] for c in ccms]            # [r/g, b/g]
    mats = [c["ccm"] for c in ccms]                # 9 each, row-major

    lsc = np.load(os.path.join(DATA, "gc2607_lsc.npz"), allow_pickle=True)
    grids = lsc["grids"].astype("<f4")             # (5,4,47,63) gain
    lsc_chroma = lsc["chroma"].astype(np.float64)  # (5,2)
    gw, gh = int(lsc["grid_w"]), int(lsc["grid_h"])
    nls, nch = int(grids.shape[0]), int(grids.shape[1])
    assert grids.shape == (nls, nch, gh, gw)

    # binary LSC grids
    grids.tofile(os.path.join(DATA, "lsc_grids.bin"))

    lines = []
    lines.append("// GENERATED by tools/gen_tuning.py -- do not edit by hand.")
    lines.append("// Tuning parsed from the camera's .aiqb file (GalaxyCore GC2607).")
    lines.append("")
    lines.append("// The extracted values carry more decimal digits than f32 represents")
    lines.append("// exactly; the literals are kept verbatim from the source tuning.")
    lines.append("#![allow(clippy::excessive_precision)]")
    lines.append("")
    lines.append(f"pub const NUM_CCM: usize = {len(cct)};")
    lines.append(f"pub const LSC_NUM_LS: usize = {nls};")
    lines.append(f"pub const LSC_NCH: usize = {nch};   // Bayer channel order: Gr, R, B, Gb")
    lines.append(f"pub const LSC_GW: usize = {gw};")
    lines.append(f"pub const LSC_GH: usize = {gh};")
    lines.append("")
    lines.append("/// Correlated colour temperature (K) of each CCM, ascending.")
    lines.append("pub const CCM_CT: [f32; NUM_CCM] = [" +
                 ", ".join(fmt_f32(c) for c in cct) + "];")
    lines.append("")
    lines.append("/// White locus chromaticity [r/g, b/g] per CCM, for CCT estimation.")
    lines.append("pub const CCM_LOCUS: [[f32; 2]; NUM_CCM] = [")
    for rg, bg in locus:
        lines.append(f"    [{fmt_f32(rg)}, {fmt_f32(bg)}],")
    lines.append("];")
    lines.append("")
    lines.append("/// Colour-correction matrices (row-major 3x3), luminance-preserving.")
    lines.append("pub const CCM: [[f32; 9]; NUM_CCM] = [")
    for m in mats:
        lines.append("    [" + ", ".join(fmt_f32(v) for v in m) + "],")
    lines.append("];")
    lines.append("")
    lines.append("/// LSC light-source chromaticity [r/g, b/g], for grid selection.")
    lines.append("pub const LSC_CHROMA: [[f32; 2]; LSC_NUM_LS] = [")
    for rg, bg in lsc_chroma:
        lines.append(f"    [{fmt_f32(rg)}, {fmt_f32(bg)}],")
    lines.append("];")
    lines.append("")

    out = os.path.join(SRC, "tuning_data.rs")
    open(out, "w").write("\n".join(lines) + "\n")

    print(f"CCM: {len(cct)} light sources, CT={cct}")
    print(f"LSC: {nls} light sources x {nch} channels, grid {gw}x{gh}, "
          f"gain {grids.min():.3f}..{grids.max():.3f}")
    print(f"-> {out}")
    print(f"-> {os.path.join(DATA, 'lsc_grids.bin')} "
          f"({grids.size * 4} bytes)")


if __name__ == "__main__":
    main()
