#!/usr/bin/env python3
"""Generate Rust tuning data from the extracted sensor tuning.

Inputs (in ../data, relative to this script):
  gc2607_ccms.json  -- 5 CCMs with cct, chroma [r/g, b/g], ccm[9]
  gc2607_lsc.npz    -- LSC grids (5,4,47,63) float gain, chroma (5,2), scale

Outputs:
  ../src/tuning_data.rs  -- const arrays (CCT, locus, CCM, LSC chroma, dims)
  ../data/lsc_grids.bin  -- f32 LE, order [ls][ch][gh][gw], values already gain
                            (raw/scale), included via include_bytes! in Rust.
"""
import json
import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
SRC = os.path.join(HERE, "..", "src")


def fmt_f32(x):
    return f"{float(x):.9g}f32"


def main():
    ccms = json.load(open(os.path.join(DATA, "gc2607_ccms.json")))
    ccms.sort(key=lambda c: c["cct"])
    cct = [c["cct"] for c in ccms]
    locus = [c["chroma"] for c in ccms]            # [r/g, b/g]
    mats = [c["ccm"] for c in ccms]                # 9 each, row-major

    lsc = np.load(os.path.join(DATA, "gc2607_lsc.npz"), allow_pickle=True)
    grids = lsc["grids"].astype("<f4")             # (5,4,47,63) gain
    lsc_chroma = lsc["chroma"].astype(np.float64)  # (5,2)
    gw, gh = int(lsc["grid_w"]), int(lsc["grid_h"])
    nls, nch = int(grids.shape[0]), int(grids.shape[1])
    assert grids.shape == (nls, nch, gh, gw)

    # Advanced (hue-sectored) colour matrices (optional: only if extracted).
    # 24 per-sector 3x3 matrices per light source. The light sources are stored
    # in an arbitrary order; sort them by CCT so they align with CCM above, and
    # verify the CCT set matches the CCMs exactly (same calibration points).
    acm_path = os.path.join(DATA, "gc2607_acm.npz")
    acm = None
    if os.path.exists(acm_path):
        z = np.load(acm_path, allow_pickle=True)
        a_cct = z["cct"].astype(np.int64)
        order = np.argsort(a_cct)
        a_cct = a_cct[order]
        advanced = z["advanced"].astype(np.float64)[order]   # (L,S,3,3) sorted
        hues = z["hues"].astype(np.int64)                    # sector upper edges
        nsec = int(advanced.shape[1])
        assert advanced.shape == (nls, nsec, 3, 3), advanced.shape
        assert list(a_cct) == list(cct), (
            f"ACM CCT {list(a_cct)} != CCM CCT {list(cct)}")
        # Sector centres: each sector spans (edge[i-1], edge[i]] with edge[-1]=0.
        edges = np.concatenate([[0], hues])
        centres = (edges[:-1] + edges[1:]) / 2.0
        steps = np.diff(centres)
        assert np.allclose(steps, steps[0]), f"non-uniform sector centres: {centres}"
        hue0 = float(centres[0])
        hue_step = float(steps[0])
        acm = (advanced, nsec, hue0, hue_step)

    # binary LSC grids
    grids.tofile(os.path.join(DATA, "lsc_grids.bin"))

    # Lateral chromatic aberration (optional: only if extracted). 4 grids of
    # absolute sub-pixel shift of blue/red relative to green, order
    # [blue_x, blue_y, red_x, red_y], written as a flat f32 LE blob.
    lca_path = os.path.join(DATA, "gc2607_lca.npz")
    lca = None
    if os.path.exists(lca_path):
        z = np.load(lca_path, allow_pickle=True)
        lca_grids = z["grids"].astype("<f4")       # (4, gh, gw)
        lca_center = z["optical_center"].astype(np.int64)
        lca_cell = z["cell_size"].astype(np.int64)
        lca = (lca_grids, lca_center, lca_cell)
        assert lca_grids.shape[0] == 4
        lca_grids.tofile(os.path.join(DATA, "lca_grids.bin"))

    lines = []
    lines.append("// GENERATED by tools/gen_tuning.py -- do not edit by hand.")
    lines.append("// Tuning parsed from the camera's .aiqb file (GalaxyCore GC2607).")
    lines.append("")
    lines.append("// The extracted values carry more decimal digits than f32 represents")
    lines.append("// exactly; the literals are kept verbatim from the source tuning.")
    lines.append("#![allow(clippy::excessive_precision)]")
    lines.append("")
    lines.append(f"pub const NUM_CCM: usize = {len(cct)};")
    lines.append(f"pub const LSC_NUM_LS: usize = {nls};")
    lines.append(f"pub const LSC_NCH: usize = {nch};   // Bayer channel order: Gr, R, B, Gb")
    lines.append(f"pub const LSC_GW: usize = {gw};")
    lines.append(f"pub const LSC_GH: usize = {gh};")
    lines.append("")
    lines.append("/// Correlated colour temperature (K) of each CCM, ascending.")
    lines.append("pub const CCM_CT: [f32; NUM_CCM] = [" +
                 ", ".join(fmt_f32(c) for c in cct) + "];")
    lines.append("")
    lines.append("/// White locus chromaticity [r/g, b/g] per CCM, for CCT estimation.")
    lines.append("pub const CCM_LOCUS: [[f32; 2]; NUM_CCM] = [")
    for rg, bg in locus:
        lines.append(f"    [{fmt_f32(rg)}, {fmt_f32(bg)}],")
    lines.append("];")
    lines.append("")
    lines.append("/// Colour-correction matrices (row-major 3x3), luminance-preserving.")
    lines.append("pub const CCM: [[f32; 9]; NUM_CCM] = [")
    for m in mats:
        lines.append("    [" + ", ".join(fmt_f32(v) for v in m) + "],")
    lines.append("];")
    lines.append("")
    lines.append("/// LSC light-source chromaticity [r/g, b/g], for grid selection.")
    lines.append("pub const LSC_CHROMA: [[f32; 2]; LSC_NUM_LS] = [")
    for rg, bg in lsc_chroma:
        lines.append(f"    [{fmt_f32(rg)}, {fmt_f32(bg)}],")
    lines.append("];")
    lines.append("")

    if acm is not None:
        advanced, nsec, hue0, hue_step = acm
        lines.append("// Advanced hue-sectored colour matrices (CMC id=25).")
        lines.append("/// Number of hue sectors (3x3 matrices) per CCM.")
        lines.append(f"pub const ACM_NSEC: usize = {nsec};")
        lines.append("/// Centre hue (deg) of sector 0; sector centres are evenly spaced.")
        lines.append(f"pub const ACM_HUE0: f32 = {fmt_f32(hue0)};")
        lines.append("/// Hue step (deg) between adjacent sector centres.")
        lines.append(f"pub const ACM_HUE_STEP: f32 = {fmt_f32(hue_step)};")
        lines.append("/// Per-sector colour matrices (row-major 3x3), one set per CCM (by CCT),")
        lines.append("/// each luminance-preserving. Indexed [ccm][sector].")
        lines.append("pub const ACM: [[[f32; 9]; ACM_NSEC]; NUM_CCM] = [")
        for ls_mats in advanced:                       # (S,3,3) per CCM
            lines.append("    [")
            for m in ls_mats:                          # (3,3)
                flat = m.reshape(9)
                lines.append("        [" + ", ".join(fmt_f32(v) for v in flat) + "],")
            lines.append("    ],")
        lines.append("];")
        lines.append("")

    if lca is not None:
        lca_grids, lca_center, lca_cell = lca
        _, lgh, lgw = lca_grids.shape
        lines.append("// Lateral chromatic aberration correction (CMC id=29).")
        lines.append("/// LCA grid dimensions (points), shared by all four shift grids.")
        lines.append(f"pub const LCA_GW: usize = {lgw};")
        lines.append(f"pub const LCA_GH: usize = {lgh};")
        lines.append("/// Grid cell size in native sensor pixels (distance between grid points).")
        lines.append(f"pub const LCA_CELL_X: f32 = {int(lca_cell[0])}.0;")
        lines.append(f"pub const LCA_CELL_Y: f32 = {int(lca_cell[1])}.0;")
        lines.append("/// Optical centre (native px) where lateral aberration is zero.")
        lines.append(f"pub const LCA_CENTER_X: f32 = {int(lca_center[0])}.0;")
        lines.append(f"pub const LCA_CENTER_Y: f32 = {int(lca_center[1])}.0;")
        lines.append("")

    out = os.path.join(SRC, "tuning_data.rs")
    open(out, "w").write("\n".join(lines) + "\n")

    print(f"CCM: {len(cct)} light sources, CT={cct}")
    if acm is not None:
        advanced, nsec, hue0, hue_step = acm
        print(f"ACM: {nsec} sectors x {len(cct)} CCMs, centre0={hue0} step={hue_step} deg, "
              f"value range {advanced.min():.3f}..{advanced.max():.3f}")
    print(f"LSC: {nls} light sources x {nch} channels, grid {gw}x{gh}, "
          f"gain {grids.min():.3f}..{grids.max():.3f}")
    if lca is not None:
        lca_grids, _, lca_cell = lca
        print(f"LCA: 4 grids {lca_grids.shape[2]}x{lca_grids.shape[1]}, "
              f"cell {int(lca_cell[0])}x{int(lca_cell[1])} px, "
              f"shift {lca_grids.min():.3f}..{lca_grids.max():.3f} px")
    print(f"-> {out}")
    print(f"-> {os.path.join(DATA, 'lsc_grids.bin')} "
          f"({grids.size * 4} bytes)")
    if lca is not None:
        print(f"-> {os.path.join(DATA, 'lca_grids.bin')}")


if __name__ == "__main__":
    main()
