// GENERATED by tools/gen_tuning.py -- do not edit by hand.
// Tuning parsed from the camera's .aiqb file (GalaxyCore GC2607).

// The extracted values carry more decimal digits than f32 represents exactly;
// the literals are kept verbatim from the source tuning rather than trimmed.
#![allow(clippy::excessive_precision)]

pub const NUM_CCM: usize = 5;
pub const LSC_NUM_LS: usize = 5;
pub const LSC_NCH: usize = 4;   // Bayer channel order: Gr, R, B, Gb
pub const LSC_GW: usize = 63;
pub const LSC_GH: usize = 47;

/// Correlated colour temperature (K) of each CCM, ascending.
pub const CCM_CT: [f32; NUM_CCM] = [2963f32, 3803f32, 4049f32, 4779f32, 6426f32];

/// White locus chromaticity [r/g, b/g] per CCM, for CCT estimation.
pub const CCM_LOCUS: [[f32; 2]; NUM_CCM] = [
    [0.717171729f32, 0.371717215f32],
    [0.58166492f32, 0.457323492f32],
    [0.522837698f32, 0.437317789f32],
    [0.478260905f32, 0.552335024f32],
    [0.408805013f32, 0.685534596f32],
];

/// Colour-correction matrices (row-major 3x3), luminance-preserving.
pub const CCM: [[f32; 9]; NUM_CCM] = [
    [1.79172516f32, -0.584244072f32, -0.207481071f32, -0.456043243f32, 1.82615364f32, -0.370110333f32, -0.222970799f32, -1.12957644f32, 2.35254717f32],
    [2.09484959f32, -0.946784437f32, -0.148065105f32, -0.389820307f32, 1.72837877f32, -0.338558525f32, -0.117032006f32, -0.681227088f32, 1.79825914f32],
    [2.52014709f32, -1.41827655f32, -0.101870514f32, -0.446843684f32, 1.6838845f32, -0.237040803f32, -0.0941111073f32, -0.677052855f32, 1.77116394f32],
    [2.05624533f32, -0.90016222f32, -0.156083137f32, -0.336227357f32, 1.77701521f32, -0.440787882f32, -0.0982201248f32, -0.653623283f32, 1.75184345f32],
    [2.1776948f32, -1.05733502f32, -0.120359942f32, -0.30370903f32, 1.78307188f32, -0.479362875f32, -0.0946084484f32, -0.533726811f32, 1.62833524f32],
];

/// LSC light-source chromaticity [r/g, b/g], for grid selection.
pub const LSC_CHROMA: [[f32; 2]; LSC_NUM_LS] = [
    [0.750948489f32, 0.357646495f32],
    [0.510686576f32, 0.51606971f32],
    [0.445347905f32, 0.624467075f32],
    [0.538944721f32, 0.40706861f32],
    [0.606908023f32, 0.418329f32],
];

